// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdveWejhluX6yj6GLSIW157c4HN98yY_I',
    appId: '1:345437538018:web:ecbd7a16fb627c0dc100bb',
    messagingSenderId: '345437538018',
    projectId: 'push-notifications-8677d',
    authDomain: 'push-notifications-8677d.firebaseapp.com',
    storageBucket: 'push-notifications-8677d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf91MMc61oB6kD5kA29rLJjX_P0xo0cAY',
    appId: '1:345437538018:android:620290619c03c46fc100bb',
    messagingSenderId: '345437538018',
    projectId: 'push-notifications-8677d',
    storageBucket: 'push-notifications-8677d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARLVazSEv4BmHOLAJLRH4ZBG7PGjyhhWE',
    appId: '1:345437538018:ios:10ec61841c2bf955c100bb',
    messagingSenderId: '345437538018',
    projectId: 'push-notifications-8677d',
    storageBucket: 'push-notifications-8677d.firebasestorage.app',
    iosBundleId: 'com.example.kishanSathiFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARLVazSEv4BmHOLAJLRH4ZBG7PGjyhhWE',
    appId: '1:345437538018:ios:10ec61841c2bf955c100bb',
    messagingSenderId: '345437538018',
    projectId: 'push-notifications-8677d',
    storageBucket: 'push-notifications-8677d.firebasestorage.app',
    iosBundleId: 'com.example.kishanSathiFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdveWejhluX6yj6GLSIW157c4HN98yY_I',
    appId: '1:345437538018:web:58a027d19d372c0cc100bb',
    messagingSenderId: '345437538018',
    projectId: 'push-notifications-8677d',
    authDomain: 'push-notifications-8677d.firebaseapp.com',
    storageBucket: 'push-notifications-8677d.firebasestorage.app',
  );
}
