name: kishan_sathi_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  http: ^1.2.2
  shared_preferences: ^2.3.3
  file_picker: ^8.1.4
  image_picker: ^1.0.7
  intl: ^0.19.0
  dartz: ^0.10.1  # Functional programming (Either, Option)
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^19.5.0
  flutter_dotenv: ^5.2.1
  provider: ^6.1.1  
  khalti_checkout_flutter: ^1.0.0-dev.9
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

  esewa_flutter_sdk: 
    path: ./external_sdk/esewa_sdk/esewa_flutter_sdk/esewa_flutter_sdk
  test: ^1.25.15
       

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/
    - assets/icons/Kishan_sathi_logo.png
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/icons/Kishan_sathi_logo.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/Kishan_sathi_logo.png  