# Generated by Django 4.2.5 on 2025-11-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='degree_certificate',
            field=models.FileField(blank=True, help_text='Upload your degree certificate (PDF, JPG, PNG)', null=True, upload_to='doctor_certificates/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='doctor_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('doctor', 'Agricultural Consultant'), ('admin', 'Admin')], default='buyer', max_length=10),
        ),
    ]
