# Generated by Django 5.2.7 on 2026-03-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_user_device_type_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Optional user profile picture', null=True, upload_to='profile_pictures/'),
        ),
    ]
