# Generated by Django 4.2.5 on 2025-12-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Questions', 'Questions'), ('Tips', 'Tips'), ('News', 'News')], default='General', max_length=20),
        ),
    ]
