# Generated by Django 5.2.7 on 2026-03-21 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessKhaltiAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khalti_id', models.CharField(help_text='Business Khalti ID (phone number)', max_length=20)),
                ('account_name', models.CharField(help_text='Name on the Khalti account', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='khalti_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Khalti Account',
                'verbose_name_plural': 'Business Khalti Accounts',
                'db_table': 'business_khalti_account',
            },
        ),
        migrations.CreateModel(
            name='KhaltiPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(blank=True, help_text='Internal transaction reference created after verification', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pidx', models.CharField(blank=True, max_length=255, null=True)),
                ('khalti_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_order_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('verified', 'Verified')], default='initiated', max_length=20)),
                ('khalti_response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='khalti_payments', to=settings.AUTH_USER_MODEL)),
                ('cart', models.ForeignKey(blank=True, help_text='Related buyer cart at checkout time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khalti_payments', to='buyer.cart')),
            ],
            options={
                'verbose_name': 'Khalti Payment Record',
                'verbose_name_plural': 'Khalti Payment Records',
                'db_table': 'khalti_payment_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
